version: "3.8"

services:
  db:
    image: postgres:16
    container_name: musicplayer-postgres
    environment:
      POSTGRES_DB: musicplayer
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: